import {
  AppWindow,
  AudioLines,
  BookOpen,
  Cable,
  Box,
  Camera,
  CalendarClock,
  Captions,
  ChartColumn,
  Clapperboard,
  Film,
  Gavel,
  Globe,
  Grid2x2,
  HandCoins,
  Image,
  Images,
  LayoutTemplate,
  ListMusic,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Music,
  PaintBucket,
  PenTool,
  RectangleHorizontal,
  ScreenShare,
  Scroll,
  Spotlight,
  Table2,
  Ticket,
  Timer,
  Trophy,
  Type,
  UserRound,
  Users,
  Video,
  Rows3,
  CircleHelp,
  PanelBottom,
  type LucideIcon,
} from 'lucide-react';

/** A line icon for each kind of input (Add input, menus). */
export const KIND_ICON: Record<string, LucideIcon> = {
  camera: Camera,
  decklink: Cable,
  video: Film,
  image: Image,
  color: PaintBucket,
  pattern: Rows3,
  countdown: Timer,
  pesukim: Scroll,
  text: Type,
  credits: Clapperboard,
  split: Grid2x2,
  slideshow: Images,
  stream: Video,
  raffle: Ticket,
  fundraiser: HandCoins,
  graphic: PenTool,
  titler: PanelBottom,
  seating: Table2,
  trivia: CircleHelp,
  scripture: BookOpen,
  zmanim: CalendarClock,
  auction: Gavel,
  wall: MessagesSquare,
  guest: UserRound,
  comment: MessageSquareText,
  poll: ChartColumn,
  lyrics: ListMusic,
  screen: ScreenShare,
  scoreboard: Trophy,
  browser: Globe,
  logo3d: Box,
  visuals: Spotlight,
  microphone: Mic,
  sound: Music,
};

/** A line icon for each group of inputs in Add input. */
export const GROUP_ICON: LucideIcon[] = [Users, Film, Captions, AppWindow, LayoutTemplate, AudioLines];

export const kindIcon = (kind: string): LucideIcon => KIND_ICON[kind] ?? RectangleHorizontal;
