// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenId } from "./ScreenId";
import type { SourceId } from "./SourceId";

/**
 * Why an action was refused. The show is never changed when this happens.
 */
export type ActionError = { "code": "unknownSource", id: SourceId, } | { "code": "duplicateSource", id: SourceId, } | { "code": "notAVideo", id: SourceId, } | { "code": "nothingInPreview", screen: ScreenId, } | { "code": "monitorIsTextOnly" } | { "code": "invalidValue", field: string, reason: string, };
