// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionKind } from "./TransitionKind";

/**
 * A transition that is currently running (or has just finished) on a screen.
 */
export type ActiveTransition = { kind: TransitionKind, durationMs: number, startedAt: number, };
