// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";

/**
 * Everything that can be adjusted on a picture. The defaults change nothing.
 */
export type Adjust = { 
/**
 * -3 – 3 stops.
 */
exposure: number, 
/**
 * -100 – 100 (also contrast, highlights, shadows, tint, saturation).
 */
brightness: number, contrast: number, highlights: number, shadows: number, 
/**
 * 0.5 – 2.
 */
gamma: number, 
/**
 * White balance, 2500 – 9000 K; 5600 changes nothing, higher is warmer.
 */
temperature: number, tint: number, saturation: number, 
/**
 * 0 – 100.
 */
sharpness: number, cropLeft: number, cropRight: number, cropTop: number, cropBottom: number, 
/**
 * 100 – 400 %.
 */
zoom: number, 
/**
 * -100 – 100.
 */
panX: number, panY: number, 
/**
 * -180 – 180 degrees.
 */
rotate: number, flipH: boolean, flipV: boolean, blur: Effect, vignette: Effect, blackWhite: Effect, grain: Effect, };
