// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppStep } from "./AppStep";

/**
 * A request left for the control window, numbered so each runs once.
 */
export type AppRequest = { seq: number, step: AppStep, };
