// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something only the control window can do.
 */
export type AppStep = { "command": "record", on: boolean, } | { "command": "stream", on: boolean, } | { "command": "replay", seconds: number, slow: boolean, } | { "command": "mark" };
