// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";

/**
 * What happens when the countdown reaches zero.
 */
export type AtZero = { "type": "hold" } | { "type": "showText" } | { "type": "hide" } | { "type": "takeNext" } | { "type": "blank" } | { "type": "cutTo", sourceId: SourceId, };
