// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuctionItem } from "./AuctionItem";

export type Auction = { title: string, 
/**
 * "$", "₪", "€", "£"…
 */
currency: string, items: Array<AuctionItem>, 
/**
 * The item being sold now.
 */
current: number, 
/**
 * Phones may bid now.
 */
open: boolean, 
/**
 * Bidding on the current item ends at this time (none: until the operator says "Sold").
 */
endsAt: number | null, 
/**
 * When the last bid came in (the screen flashes).
 */
lastBidAt: number, 
/**
 * When the current item was sold (the celebration).
 */
soldAt: number, nextId: number, joinUrl: string, joinQr: string, showJoin: boolean, };
