// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bid } from './Bid';

export type AuctionItem = {
  /**
   * 0 for a new item (it gets one when added).
   */
  id: number;
  name: string;
  /**
   * A line about it ("Donated by the Levi family").
   */
  detail: string;
  /**
   * A picture of it (a file on this computer), or empty.
   */
  photo: string;
  /**
   * The lowest first bid.
   */
  start: number;
  /**
   * Each bid is at least this much more than the last.
   */
  step: number;
  bids: Array<Bid>;
  /**
   * Sold to the highest bid.
   */
  sold: boolean;
};
