// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bus } from './Bus';
import type { SourceId } from './SourceId';

/**
 * The mixes and the headphone solo. The Stream mix's level is
 * `Show::master_volume`.
 */
export type AudioMix = {
  masterMuted: boolean;
  a: Bus;
  b: Bus;
  /**
   * The source heard in the headphones on its own (none: headphones hear the Stream mix).
   */
  solo: SourceId | null;
};
