// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where each mix is played.
 */
export type AudioOutputId = "master" | "a" | "b" | "headphones";
