// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sound device (speakers, headphones, audio interface output) each mix
 * goes to. For the Stream mix `None` means the computer's default speakers;
 * for Hall, Recording and Headphones `None` means not played anywhere, so a
 * mix is never doubled on the same speakers by accident.
 */
export type AudioOutputs = { master: string | null; a: string | null; b: string | null; headphones: string | null };
