// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";

/**
 * Going through the cameras by itself on the Live Screen.
 */
export type AutoSwitch = { on: boolean, 
/**
 * The cameras (or any inputs) it goes between, in order.
 */
cameras: Array<SourceId>, 
/**
 * Each shot lasts between these, seconds (the same for a steady beat).
 */
minS: number, maxS: number, 
/**
 * Mixed up (never the same twice in a row) instead of in order.
 */
random: boolean, 
/**
 * A quick mix between cameras instead of a cut.
 */
mix: boolean, 
/**
 * When the next switch is due.
 */
nextAt: number, 
/**
 * Changes every switch, for the mixed-up order and shot lengths.
 */
seed: number, };
