// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameWho } from "./FrameWho";

/**
 * A wide camera that zooms in on and follows the people in it.
 */
export type AutoFrame = { enabled: boolean, who: FrameWho, 
/**
 * How close the shot is, 0 (loose, lots of room) – 1 (tight).
 */
tightness: number, 
/**
 * How quickly it moves to follow, 0 (slow and calm) – 1 (quick).
 */
speed: number, 
/**
 * Never zoom in further than the camera stays sharp.
 */
keepSharp: boolean, };
