// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens to the background behind the people (no green screen needed).
 */
export type BackgroundMode = "keep" | "blur" | "remove" | "picture" | "set";
