// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenId } from './ScreenId';
import type { SourceId } from './SourceId';

/**
 * The backup lineup (automatic failover): when the input on air loses its
 * picture (a camera unplugged, a stream lost), the next input in the lineup
 * that still has a picture goes on air by itself. The control window sees
 * the picture stop and makes the switch; the engine only keeps the plan.
 */
export type Backup = {
  /**
   * On (the default).
   */
  on: boolean;
  /**
   * The inputs in order. Empty: automatic (the cameras in input order,
   * then the logo).
   */
  lineup: Array<SourceId>;
  /**
   * How long without a new picture before an input counts as lost, ms.
   */
  lostAfterMs: number;
  /**
   * A quick mix instead of a cut, ms (0: a cut).
   */
  fadeMs: number;
  /**
   * Go back to the input by itself when its picture returns (off: the
   * operator is asked).
   */
  switchBack: boolean;
  /**
   * The screens it looks after.
   */
  screens: Array<ScreenId>;
};
