// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundMode } from './BackgroundMode';

export type Background = {
  mode: BackgroundMode;
  /**
   * How strong the blur is, 0 – 1.
   */
  blur: number;
  /**
   * The picture behind the people (mode Picture).
   */
  picture?: string | null;
  /**
   * How soft the edge around people is, 0 – 1.
   */
  edge: number;
  /**
   * The virtual set (mode Set), e.g. "news".
   */
  set?: string | null;
};
