// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomFont } from './CustomFont';
import type { TextAlign } from './TextAlign';
import type { TextDesign } from './TextDesign';
import type { TextEntrance } from './TextEntrance';

/**
 * The event's look, applied to all titles, songs and scoreboards at once.
 */
export type Brand = {
  font: string;
  textColor: string;
  /**
   * Bars, lines and name boxes.
   */
  accent: string;
  boxColor: string;
  /**
   * 0 – 100.
   */
  boxOpacity: number;
  design: TextDesign;
  /**
   * Name titles' (lower thirds') text size, px of a 1080 frame.
   */
  size: number;
  weight: number;
  italic: boolean;
  uppercase: boolean;
  align: TextAlign;
  outline: number;
  outlineColor: string;
  shadow: boolean;
  /**
   * A box behind the words (Box, Accent bar).
   */
  boxOn: boolean;
  padding: number;
  radius: number;
  /**
   * Line height, % of the size.
   */
  lineHeight: number;
  /**
   * Letter spacing, px.
   */
  letterSpacing: number;
  /**
   * The second line: color ("" same), size (% of the first), font ("" same).
   */
  subColor: string;
  subSize: number;
  subFont: string;
  border: number;
  borderColor: string;
  /**
   * Where name titles sit: % from the side and from the bottom.
   */
  x: number;
  y: number;
  animate: boolean;
  entrance: TextEntrance;
  /**
   * Font files added for this event.
   */
  fonts: Array<CustomFont>;
};
