// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextDesign } from "./TextDesign";

/**
 * The event's look, applied to all titles, songs and scoreboards at once.
 */
export type Brand = { font: string, textColor: string, 
/**
 * Bars, lines and name boxes.
 */
accent: string, boxColor: string, 
/**
 * 0 – 100.
 */
boxOpacity: number, design: TextDesign, };
