// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An extra mix (A: hall speakers, B: recording).
 */
export type Bus = { name: string, 
/**
 * 0.0 – 1.0
 */
volume: number, muted: boolean, };
