// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Changes to a mix. Fields left out stay as they are.
 */
export type BusPatch = { name?: string; volume?: number; muted?: boolean };
