// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraShot } from './CameraShot';
import type { CameraValue } from './CameraValue';

/**
 * A camera's own settings, kept with the event.
 */
export type CameraControls = {
  /**
   * The settings now (only those changed from the camera's own).
   */
  values: Array<CameraValue>;
  shots: Array<CameraShot>;
};
