// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraValue } from './CameraValue';

/**
 * A saved shot: the settings to go back to.
 */
export type CameraShot = { name: string; values: Array<CameraValue> };
