// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One camera setting ("zoom", "focusDistance", "exposureMode"…) and its value.
 * Modes are numbers too: 0 manual, 1 automatic.
 */
export type CameraValue = { name: string, value: number, };
