// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptionPlace } from "./CaptionPlace";
import type { SourceId } from "./SourceId";

export type Captions = { on: boolean, 
/**
 * The microphone listened to (None: everything in the Stream mix).
 */
listen?: SourceId | null, 
/**
 * Also written in the stream picture (for sites without closed
 * captions). The recording stays clean.
 */
inPicture: boolean, place: CaptionPlace, 
/**
 * Text size, 0.6 – 1.6 (1: the usual).
 */
size: number, 
/**
 * Lines of text at once, 1 – 3.
 */
lines: number, 
/**
 * The language spoken: a code like "en" or "he", or "auto" (worked out).
 */
language: string, 
/**
 * The most accurate (bigger, slower) model for languages other than
 * English.
 */
best: boolean, };
