// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatPlatform } from "./ChatPlatform";

export type ChatComment = { author: string, text: string, platform: ChatPlatform, };
