// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Green screen: a colour taken out of the picture so what is behind shows.
 */
export type ChromaKey = { enabled: boolean, 
/**
 * The colour taken out (usually the green of the screen).
 */
color: string, 
/**
 * How close to the colour is taken out, 0 – 1.
 */
similarity: number, 
/**
 * How soft the edge is, 0 – 1.
 */
smoothness: number, 
/**
 * How much green reflected on people is taken away, 0 – 1.
 */
spill: number, };
