// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatComment } from './ChatComment';
import type { CommentPlace } from './CommentPlace';

/**
 * A comment input: the comment showing now (None: nothing).
 */
export type CommentCard = {
  comment: ChatComment | null;
  /**
   * When it last changed (for its animation).
   */
  changedAt: number;
  place: CommentPlace;
  /**
   * The card's color.
   */
  accent: string;
};
