// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtZero } from './AtZero';
import type { TimerFormat } from './TimerFormat';

/**
 * The countdown. It goes on a screen as a Countdown input (lined up in
 * Next and taken to air like any other input); the stage monitor can show
 * it too. Its time is stored as "ends at" while running and "time
 * left" while paused, so every window can work out the time on its own.
 */
export type Countdown = {
  /**
   * Length it starts from (and returns to on reset).
   */
  lengthMs: number;
  /**
   * While running: the moment it reaches zero.
   */
  endsAt: number | null;
  /**
   * While paused: time left.
   */
  remainingMs: number;
  /**
   * Shown above the numbers, e.g. "Starting soon".
   */
  label: string;
  /**
   * Shown at zero when [`AtZero::ShowText`] is chosen.
   */
  endText: string;
  format: TimerFormat;
  atZero: AtZero;
  /**
   * True once the at-zero action has run, so it runs only once.
   */
  fired: boolean;
};
