// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtZero } from "./AtZero";
import type { TimerFormat } from "./TimerFormat";

/**
 * Changes to how the countdown looks and ends. Fields left out stay as they are.
 */
export type CountdownPatch = { label?: string, endText?: string, format?: TimerFormat, atZero?: AtZero, };
