// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditsMode } from "./CreditsMode";

/**
 * Credits and where they are.
 */
export type Credits = { 
/**
 * Shown first, big (e.g. "Thank you").
 */
title: string, 
/**
 * One per line; "Name — role" shows the role smaller.
 */
names: Array<string>, mode: CreditsMode, 
/**
 * Roll speed in px (of a 1080 frame) per second.
 */
speed: number, 
/**
 * Pages: how long each page shows.
 */
pageMs: number, background: string, color: string, font: string, 
/**
 * Size of a name, px of a 1080 frame.
 */
size: number, 
/**
 * Playing (rolling or turning pages).
 */
playing: boolean, 
/**
 * Position in ms of playing time at `at` (like a video).
 */
posMs: number, at: number, };
