// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueTrigger } from "./CueTrigger";
import type { Step } from "./Step";

/**
 * One cue.
 */
export type Cue = { id: string, 
/**
 * The section it belongs to, e.g. "Opening".
 */
section: string, name: string, trigger: CueTrigger, 
/**
 * How long it runs (for the timeline, and for a next cue set to
 * "after the previous").
 */
lengthMs: number | null, steps: Array<Step>, };
