// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a cue starts.
 */
export type CueTrigger = { type: 'manual' } | { type: 'clock'; time: string } | { type: 'afterPrevious' };
