// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A font from a file (TTF, OTF, WOFF), usable by name like an installed one.
 */
export type CustomFont = { name: string, path: string, };
