// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataFeed = { 
/**
 * The file (empty: none).
 */
path: string, 
/**
 * How often it is read again, ms.
 */
everyMs: number, 
/**
 * The column names (the file's first row).
 */
headers: Array<string>, rows: Array<Array<string>>, 
/**
 * The row titles take their words from (from 0).
 */
row: number, 
/**
 * Why the file could not be read (empty: fine).
 */
error: string, updatedAt: number, };
