// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stroke } from './Stroke';

/**
 * A drawing input: the strokes on it now.
 */
export type Drawing = {
  strokes: Array<Stroke>;
  /**
   * When it last changed.
   */
  changedAt: number;
};
