// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A draw in progress (or just finished): the winner is chosen when it starts.
 */
export type Draw = { startedAt: number, winner: number, durationMs: number, };
