// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An effect that can be switched on, with how strong it is (0 – 100).
 */
export type Effect = { on: boolean; amount: number };
