// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementKind } from "./ElementKind";
import type { Entrance } from "./Entrance";
import type { TextAlign } from "./TextAlign";

export type Element = { id: number, kind: ElementKind, 
/**
 * Where and how big, in % of the frame's width and height.
 */
x: number, y: number, w: number, h: number, 
/**
 * Text: the words ({Column} for the data file).
 */
text: string, font: string, 
/**
 * Text size in % of the frame height.
 */
size: number, weight: number, italic: boolean, align: TextAlign, 
/**
 * Text colour, or the box's colour.
 */
color: string, 
/**
 * Box corners, in % of the frame height.
 */
radius: number, 
/**
 * 0 – 1.
 */
opacity: number, 
/**
 * Image: the picture file.
 */
path: string, shadow: boolean, 
/**
 * How it comes in, and how long after the graphic starts (ms).
 */
entrance: Entrance, delayMs: number, };
