// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Brand } from "./Brand";
import type { GuestWifi } from "./GuestWifi";
import type { Place } from "./Place";
import type { SafeScreen } from "./SafeScreen";

/**
 * The event and its emergency plan.
 */
export type EventInfo = { name: string, 
/**
 * Picture file of the event logo.
 */
logo: string | null, 
/**
 * What a screen shows when a camera or video on it stops working.
 */
onFailure: SafeScreen, 
/**
 * What the Live and Back screens show while PANIC is on.
 */
panicShows: SafeScreen, 
/**
 * The setup questions have been answered (or skipped).
 */
setUp: boolean, 
/**
 * The event's look: colors and font for every title.
 */
brand: Brand, 
/**
 * The guests' Wi-Fi, shown as a code to join it next to the audience page's code.
 */
wifi: GuestWifi, 
/**
 * Where the event is (Hebrew date, zmanim, candle lighting).
 */
place: Place, };
