// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SafeScreen } from "./SafeScreen";

/**
 * Changes to the event. Fields left out stay as they are.
 */
export type EventPatch = { name?: string, 
/**
 * A picture path, or "" to remove the logo.
 */
logo?: string, onFailure?: SafeScreen, panicShows?: SafeScreen, setUp?: boolean, };
