// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Brand } from "./Brand";
import type { SafeScreen } from "./SafeScreen";

/**
 * The event and its emergency plan.
 */
export type EventInfo = { name: string, 
/**
 * Picture file of the event logo.
 */
logo: string | null, 
/**
 * What a screen shows when a camera or video on it stops working.
 */
onFailure: SafeScreen, 
/**
 * What the Live and Back screens show while PANIC is on.
 */
panicShows: SafeScreen, 
/**
 * The setup questions have been answered (or skipped).
 */
setUp: boolean, 
/**
 * The event's look: colours and font for every title.
 */
brand: Brand, };
