// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a picture fits into the output frame.
 */
export type Fit = "contain" | "cover";
