// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who auto-framing keeps in the shot.
 */
export type FrameWho = 'everyone' | 'main';
