// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the overlay sits, in % of the frame (0 – 100).
 */
export type Frame = { x: number; y: number; w: number; h: number };
