// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pledge } from './Pledge';

export type Fundraiser = {
  title: string;
  /**
   * "$", "₪", "€", "£"…
   */
  currency: string;
  goal: number;
  /**
   * Given before Lumora (cash, checks, online): added to the total.
   */
  starting: number;
  pledges: Array<Pledge>;
  /**
   * Phones may pledge now.
   */
  open: boolean;
  /**
   * Pledges from phones count straight away (else the operator approves each).
   */
  autoApprove: boolean;
  showDonors: boolean;
  nextId: number;
  /**
   * When the total last passed a quarter of the goal (for the celebration).
   */
  celebratedAt: number;
  joinUrl: string;
  joinQr: string;
  showJoin: boolean;
};
