// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The game clock.
 */
export type GameClock = {
  /**
   * Counts down from `length_ms` (else up from 0).
   */
  countDown: boolean;
  lengthMs: number;
  /**
   * Time already run before `since`.
   */
  runMs: number;
  /**
   * Running since then (None: stopped).
   */
  since: number | null;
};
