// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A guest who joins from their phone or computer by a link. They send
 * their camera and microphone through VDO.Ninja (free, in the browser, no
 * account); Lumora shows them like a web page input, sound included.
 */
export type Guest = { 
/**
 * The private room name in both links (letters and digits only).
 */
room: string, 
/**
 * Bumped to reload the guest's picture now.
 */
reload: number, };
