// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogoBackground } from "./LogoBackground";
import type { LogoMaterial } from "./LogoMaterial";
import type { LogoMotion } from "./LogoMotion";
import type { SceneRef } from "./SceneRef";
import type { SwingEnds } from "./SwingEnds";

/**
 * A 3D logo input.
 */
export type Logo3d = { 
/**
 * The logo picture (PNG or SVG); empty: the event logo.
 */
path: string, 
/**
 * Thickness, 0 – 60 (% of the logo's height / 2).
 */
depth: number, 
/**
 * Rounded edge, 0 – 20.
 */
bevel: number, material: LogoMaterial, 
/**
 * One colour for the whole logo; None: the logo's own colours.
 */
color: string | null, 
/**
 * Where the light comes from, -180 – 180 degrees.
 */
lightAngle: number, 
/**
 * 0 – 1.
 */
lightStrength: number, motion: LogoMotion, 
/**
 * Back and forth: how far each way, 10 – 90 degrees.
 */
swing: number, ends: SwingEnds, 
/**
 * Seconds for one turn (or one swing), 1.5 – 30.
 */
seconds: number, 
/**
 * The angle when still (and where a spin starts), -180 – 180.
 */
angle: number, 
/**
 * Moving; when off it stands at `angle`.
 */
playing: boolean, 
/**
 * Camera distance 0 (close, big) – 1 (far, small).
 */
camera: number, background: LogoBackground, bgColor: string, bgScene: SceneRef, };
