// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the logo is made of.
 */
export type LogoMaterial = 'metal' | 'glass' | 'gloss' | 'matte';
