// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Behind the logo.
 */
export type LogoBackground = 'transparent' | 'colour' | 'loop';
