// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyricsPlace } from './LyricsPlace';
import type { TextStyle } from './TextStyle';

export type Lyrics = {
  title: string;
  /**
   * The whole song; a blank line starts a new slide.
   */
  text: string;
  /**
   * The slide showing (0-based).
   */
  current: number;
  /**
   * Words hidden (between songs, during an instrumental).
   */
  blank: boolean;
  /**
   * When the slide last changed (for the fade).
   */
  changedAt: number;
  place: LyricsPlace;
  style: TextStyle;
};
