// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from "./Step";

/**
 * One macro.
 */
export type Macro = { id: string, name: string, steps: Array<Step>, 
/**
 * The key that runs it in the control window ("Ctrl+1", "F5"; empty: none).
 */
hotkey: string, };
