// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorLayout } from "./MonitorLayout";
import type { TextSize } from "./TextSize";

/**
 * Everything the stage monitor shows.
 */
export type Monitor = { 
/**
 * The message typed by the operator.
 */
message: string, 
/**
 * Whether the message is on the monitor right now.
 */
messageOn: boolean, layout: MonitorLayout, showClock: boolean, showTimer: boolean, textSize: TextSize, 
/**
 * 24-hour clock (19:42) instead of 12-hour (7:42 PM).
 */
clock24h: boolean, 
/**
 * Messages one click away. Always exactly [`QUICK_MESSAGES`] entries.
 */
quick: Array<string>, };
