// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorLayout } from "./MonitorLayout";
import type { Prompter } from "./Prompter";
import type { TextSize } from "./TextSize";

/**
 * Everything the stage monitor shows.
 */
export type Monitor = { 
/**
 * The message typed by the operator.
 */
message: string, 
/**
 * Whether the message is on the monitor right now.
 */
messageOn: boolean, layout: MonitorLayout, showClock: boolean, showTimer: boolean, 
/**
 * A song on air on the Live Screen shows its words here too (the crew
 * can turn this off).
 */
showLyrics: boolean, textSize: TextSize, 
/**
 * 24-hour clock (19:42) instead of 12-hour (7:42 PM).
 */
clock24h: boolean, 
/**
 * The time left turns amber this many seconds before the end (0: never),
 * and red in the last minute.
 */
wrapUpS: number, 
/**
 * After zero, the time over is shown in red (+1:05) instead of 0:00.
 */
overtime: boolean, 
/**
 * A bar under the time left shows how much of it has gone.
 */
progress: boolean, 
/**
 * Messages one click away. Always exactly [`QUICK_MESSAGES`] entries.
 */
quick: Array<string>, 
/**
 * The teleprompter.
 */
prompter: Prompter, };
