// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the monitor arranges the message, clock and countdown.
 */
export type MonitorLayout = "full" | "stack" | "split";
