// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorLayout } from './MonitorLayout';
import type { TextSize } from './TextSize';

/**
 * Changes to the stage monitor. Fields left out stay as they are.
 */
export type MonitorPatch = {
  message?: string;
  messageOn?: boolean;
  layout?: MonitorLayout;
  showClock?: boolean;
  showTimer?: boolean;
  showLyrics?: boolean;
  textSize?: TextSize;
  clock24h?: boolean;
};
