// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiviewLayout } from './MultiviewLayout';

/**
 * The multiview screen: every input and the screens at once, for the crew.
 */
export type Multiview = {
  /**
   * The display it fills (None: a window).
   */
  display: string | null;
  layout: MultiviewLayout;
};
