// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the multiview screen is laid out.
 */
export type MultiviewLayout = "classic" | "bothScreens" | "inputs";
