// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fit } from "./Fit";
import type { SourceId } from "./SourceId";
import type { SourceKind } from "./SourceKind";

/**
 * A new source as requested by the UI. The engine fills in and cleans up the
 * rest (id, limits, play state).
 */
export type NewSource = { 
/**
 * Leave empty to let the engine choose an id.
 */
id?: SourceId, name: string, kind: SourceKind, volume?: number, muted?: boolean, looping?: boolean, fit?: Fit, };
