// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an overlay comes in or goes out.
 */
export type OverlayAnim = 'cut' | 'fade' | 'slideLeft' | 'slideRight' | 'slideUp' | 'zoom' | 'wipe';
