// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";
import type { OverlayAnim } from "./OverlayAnim";
import type { ScreenId } from "./ScreenId";

/**
 * Changes to an overlay channel's settings. Fields left out stay as they are.
 * (Its input is chosen with `SetOverlaySource`.)
 */
export type OverlayPatch = { frame?: Frame, opacity?: number, animIn?: OverlayAnim, animOut?: OverlayAnim, animMs?: number, 
/**
 * `0` turns auto-hide off.
 */
autoHideMs?: number, screens?: Array<ScreenId>, };
