// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";
import type { OverlayAnim } from "./OverlayAnim";
import type { ScreenId } from "./ScreenId";
import type { SourceId } from "./SourceId";

/**
 * One overlay channel.
 */
export type Overlay = { sourceId: SourceId | null, frame: Frame, 
/**
 * 0.0 – 1.0
 */
opacity: number, animIn: OverlayAnim, animOut: OverlayAnim, animMs: number, 
/**
 * Goes off by itself this long after coming on (None: stays).
 */
autoHideMs: number | null, 
/**
 * The screens it goes on (Live and/or Back; never the Monitor).
 */
screens: Array<ScreenId>, 
/**
 * On air now.
 */
on: boolean, 
/**
 * Shown on the Next monitors, to set it up before it goes on air.
 */
inNext: boolean, 
/**
 * When it last came on or went off (for its animation and auto-hide).
 */
changedAt: number, };
