// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pasuk and the child who says it.
 */
export type Pasuk = { child: string, 
/**
 * The words, separated by spaces. A hyphen (-) joins two words shown together.
 */
text: string, 
/**
 * How each word sounds, word for word (the same spaces and hyphens).
 */
translit: string, 
/**
 * What each word means, word for word; "_" for a word with none.
 */
english: string, 
/**
 * What the whole pasuk means (shown with the whole pasuk).
 */
translation: string, };
