// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pasuk and the child who says it.
 */
export type Pasuk = { child: string, 
/**
 * The words, separated by spaces. A hyphen (-) joins two words shown together.
 */
text: string, };
