// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-screen map with exactly one entry for each screen.
 */
export type PerScreen<T> = { live: T, back: T, monitor: T, };
