// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the operator is.
 */
export type PesukimPlace = {
  /**
   * 0 – 11.
   */
  pasuk: number;
  word: number;
  /**
   * Showing the whole pasuk (until the next word).
   */
  whole: boolean;
  /**
   * Words hidden; the background stays.
   */
  blank: boolean;
  /**
   * The child's name, before the first word of their pasuk.
   */
  intro: boolean;
  /**
   * When the word last changed (for the word animation and auto-advance).
   */
  changedAt: number;
};
