// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PesukimMode } from "./PesukimMode";
import type { SourceId } from "./SourceId";
import type { WordChange } from "./WordChange";

/**
 * How the pesukim look.
 */
export type PesukimLook = { mode: PesukimMode, 
/**
 * Words already said stay on screen (the pasuk builds up).
 */
keepSaid: boolean, 
/**
 * The child's name in the corner.
 */
showName: boolean, 
/**
 * Background colour.
 */
background: string, 
/**
 * An input shown behind the words (a camera, usually).
 */
behind: SourceId | null, textColor: string, 
/**
 * Size of a single word, in % of the screen height.
 */
size: number, font: string, wordChange: WordChange, 
/**
 * Move to the next word by itself every this many ms while on air (None: off).
 */
autoMs: number | null, };
