// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarWords } from "./BarWords";
import type { PesukimMode } from "./PesukimMode";
import type { SourceId } from "./SourceId";
import type { TextEntrance } from "./TextEntrance";
import type { WordChange } from "./WordChange";

/**
 * How the pesukim look.
 */
export type PesukimLook = { mode: PesukimMode, 
/**
 * Words already said stay on screen (the pasuk builds up).
 */
keepSaid: boolean, 
/**
 * The child's name comes up before their pasuk.
 */
showName: boolean, 
/**
 * How the words sound, under the Hebrew.
 */
showTranslit: boolean, 
/**
 * What the words mean, under that.
 */
showEnglish: boolean, 
/**
 * The bar's design (one of the built-in ones), when no picture is chosen.
 */
design: string, 
/**
 * A picture of your own for the bar (a file on this computer), or empty.
 */
barImage: string, 
/**
 * One word at a time, or a line with the word lit.
 */
barWords: BarWords, 
/**
 * The outline around the words with no bar background (the second colour).
 */
outlineColor: string, 
/**
 * Just the words, where the bar would be (the bar's design is kept for later).
 */
plain: boolean, 
/**
 * How the bar comes on.
 */
barIn: TextEntrance, 
/**
 * The pasuk's number in a circle at the end of the bar.
 */
showNumber: boolean, 
/**
 * Background colour.
 */
background: string, 
/**
 * An input shown behind the words (a camera, usually).
 */
behind: SourceId | null, textColor: string, 
/**
 * Size of a single word, in % of the screen height.
 */
size: number, font: string, wordChange: WordChange, 
/**
 * Move to the next word by itself every this many ms while on air (None: off).
 */
autoMs: number | null, };
