// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the screen shows.
 */
export type PesukimMode = 'bar' | 'word' | 'strip' | 'pasuk';
