// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Player = {
  /**
   * The phone's own random name for itself.
   */
  key: string;
  name: string;
  score: number;
};
