// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistItem } from "./PlaylistItem";

/**
 * The list and where it is.
 */
export type Playlist = { items: Array<PlaylistItem>, 
/**
 * The item playing (or ready).
 */
current: number, 
/**
 * Go on to the next video when one ends.
 */
autoNext: boolean, 
/**
 * After the last, start again from the first.
 */
loopAll: boolean, };
