// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Play state of a video. The position is stored as "position `pos_s` at time
 * `at`", so every window can work out the current position on its own.
 */
export type Playback = { playing: boolean, posS: number, at: number, };
