// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One video in a playlist.
 */
export type PlaylistItem = { path: string, name: string, 
/**
 * Its length once known (0 until then).
 */
durationS: number, };
