// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pledge = {
  id: number;
  name: string;
  /**
   * Whole units of the currency.
   */
  amount: number;
  message: string;
  at: number;
  /**
   * Counted in the total (pledges from phones wait for the operator unless auto-approve is on).
   */
  approved: boolean;
};
