// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Poll = { question: string, options: Array<string>, 
/**
 * Votes for each answer.
 */
votes: Array<number>, 
/**
 * Taking votes now.
 */
open: boolean, 
/**
 * The bars show on screen (else only the question and answers).
 */
showResults: boolean, 
/**
 * Goes up whenever the votes start again, so old votes don't count.
 */
round: number, 
/**
 * Where phones vote, and its QR code (SVG), when shown on screen.
 */
joinUrl: string, joinQr: string, showJoin: boolean, };
