// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetButton } from './PresetButton';
import type { ScreenId } from './ScreenId';
import type { SourceId } from './SourceId';
import type { Transition } from './Transition';

/**
 * A segment of the event.
 */
export type Preset = {
  id: string;
  name: string;
  /**
   * Grouping in the list, e.g. "Speeches".
   */
  category: string;
  /**
   * The screen it works on (Live or Back).
   */
  screen: ScreenId;
  /**
   * The inputs this segment uses. While it is picked, only these show on
   * the main screen. Empty: all inputs.
   */
  sources: Array<SourceId>;
  /**
   * Transition to use while it is picked (the show's stays if none).
   */
  transition: Transition | null;
  /**
   * When picked, line its first input up in Next.
   */
  loadFirst: boolean;
  buttons: Array<PresetButton>;
};
