// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from './Step';

/**
 * A named button: its steps run in order when pressed.
 */
export type PresetButton = { name: string; steps: Array<Step> };
