// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prompter = { 
/**
 * Shown on the stage monitor instead of the usual screen.
 */
on: boolean, script: string, 
/**
 * Scrolling speed, in % of the monitor's height a second.
 */
speed: number, 
/**
 * Text size, in % of the monitor's height.
 */
size: number, 
/**
 * Mirrored left to right (for a glass prompter over a camera).
 */
mirror: boolean, 
/**
 * How far the script has moved, in % of the monitor's height, at `since` (or now, when stopped).
 */
pos: number, 
/**
 * Moving since then (None: stopped).
 */
since: number | null, };
