// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from './Question';

export type Qna = {
  /**
   * Taking questions now.
   */
  open: boolean;
  questions: Array<Question>;
  nextId: number;
};
