// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Question = {
  id: number;
  /**
   * The name they gave (may be empty).
   */
  author: string;
  text: string;
  at: number;
  /**
   * Already put on screen.
   */
  shown: boolean;
};
