// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Draw } from "./Draw";
import type { Entry } from "./Entry";

export type Raffle = { title: string, 
/**
 * The prize (shown under the title).
 */
prize: string, entries: Array<Entry>, 
/**
 * Phones may enter now.
 */
open: boolean, 
/**
 * Everyone drawn so far, in order.
 */
winners: Array<number>, draw: Draw | null, 
/**
 * Someone already drawn can win again.
 */
repeatWinners: boolean, nextId: number, 
/**
 * The audience page, and its QR code (SVG), shown while entering.
 */
joinUrl: string, joinQr: string, showJoin: boolean, };
