// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from './Step';

/**
 * Steps being run, resumed by the engine's heartbeat after a wait.
 */
export type RunningSteps = {
  /**
   * What started it (a button name), for the operator.
   */
  name: string;
  steps: Array<Step>;
  next: number;
  resumeAt: number;
};
