// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cue } from "./Cue";

/**
 * The run of show and where it is.
 */
export type RunOfShow = { cues: Array<Cue>, 
/**
 * Started (cues on the clock and "after the previous" fire by themselves).
 */
running: boolean, 
/**
 * Held: nothing fires by itself until it carries on.
 */
paused: boolean, 
/**
 * The last cue that ran.
 */
current: number | null, 
/**
 * When it ran.
 */
cueStartedAt: number, 
/**
 * When the show was started.
 */
startedAt: number, 
/**
 * The computer's local time offset from UTC, in minutes (for clock cues).
 */
utcOffsetMin: number, };
