// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A scene: music type and the scene in it (both 0-based).
 */
export type SceneRef = { bank: number, scene: number, };
