// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameClock } from "./GameClock";
import type { ScoreLink } from "./ScoreLink";
import type { ScoreStyle } from "./ScoreStyle";
import type { Team } from "./Team";

export type Scoreboard = { home: Team, away: Team, 
/**
 * "1st half", "Q3", "Set 2"… (empty: none).
 */
period: string, clock: GameClock, showClock: boolean, style: ScoreStyle, 
/**
 * A line over the full-screen board (the match or event).
 */
title: string, 
/**
 * Columns of the data file this board follows.
 */
link: ScoreLink, };
