// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which columns a scoreboard follows (empty: not linked).
 */
export type ScoreLink = { homeName: string, homeScore: string, awayName: string, awayScore: string, period: string, };
