// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three outputs Lumora drives.
 */
export type ScreenId = "live" | "back" | "monitor";
