// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureTarget } from './CaptureTarget';

export type ScreenCapture = {
  target: CaptureTarget;
  /**
   * Show the mouse pointer.
   */
  cursor: boolean;
};
