// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveTransition } from "./ActiveTransition";
import type { SourceId } from "./SourceId";

/**
 * Everything about one output screen.
 */
export type ScreenState = { 
/**
 * What is lined up next.
 */
preview: SourceId | null, 
/**
 * What is on air.
 */
program: SourceId | null, 
/**
 * What was on air before the last take (used while a transition runs).
 */
previous: SourceId | null, transition: ActiveTransition | null, 
/**
 * Manual fader position, 0.0 – 1.0.
 */
tbar: number, blank: boolean, blankChangedAt: number, flashAt: number, };
