// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptureLang } from './ScriptureLang';
import type { ScriptureLook } from './ScriptureLook';

export type Scripture = {
  /**
   * Which book (0 = Bereishis … 26 = Tehillim … 38).
   */
  book: number;
  /**
   * Chapter, from 1.
   */
  chapter: number;
  /**
   * The passage's first and last verse, from 1.
   */
  from: number;
  to: number;
  /**
   * The verse on screen now (one at a time).
   */
  current: number;
  /**
   * Show the whole passage at once instead of a verse at a time.
   */
  whole: boolean;
  lang: ScriptureLang;
  look: ScriptureLook;
  /**
   * Show "Tehillim 23:1" under the text.
   */
  showRef: boolean;
  /**
   * Nothing on screen for now.
   */
  blank: boolean;
};
