// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Seat } from "./Seat";
import type { SeatingLook } from "./SeatingLook";

export type Seating = { title: string, guests: Array<Seat>, look: SeatingLook, 
/**
 * Seconds each page of the list stays.
 */
seconds: number, 
/**
 * Phones may look up their table.
 */
open: boolean, joinUrl: string, joinQr: string, showJoin: boolean, };
