// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerScreen } from "./PerScreen";

/**
 * Settings that belong to the machine, remembered between events.
 */
export type Settings = { 
/**
 * Which physical display each screen goes to (set once, remembered).
 */
displays: PerScreen<string | null>, 
/**
 * Start videos automatically when they are taken to air.
 */
autoPlayOnTake: boolean, };
