// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioOutputs } from "./AudioOutputs";
import type { Multiview } from "./Multiview";
import type { PerScreen } from "./PerScreen";
import type { Transition } from "./Transition";

/**
 * Settings that belong to the machine, remembered between events.
 */
export type Settings = { 
/**
 * Which physical display each screen goes to (set once, remembered).
 */
displays: PerScreen<string | null>, 
/**
 * Start videos automatically when they are taken to air.
 */
autoPlayOnTake: boolean, 
/**
 * Which sound device each mix plays on.
 */
audioOutputs: AudioOutputs, 
/**
 * How long "Fade to black" takes, ms.
 */
fadeToBlackMs: number, 
/**
 * The four favourite transition buttons.
 */
favouriteTransitions: Array<Transition>, 
/**
 * The multiview screen: which display it goes to, and its layout.
 */
multiview: Multiview, };
