// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerScreen } from "./PerScreen";
import type { ScreenState } from "./ScreenState";
import type { Settings } from "./Settings";
import type { Source } from "./Source";
import type { Transition } from "./Transition";

/**
 * The whole show. This is the single source of truth.
 */
export type Show = { version: number, 
/**
 * Sources in the order they appear on screen.
 */
sources: Array<Source>, screens: PerScreen<ScreenState>, 
/**
 * The transition TAKE uses.
 */
transition: Transition, panic: boolean, panicChangedAt: number, 
/**
 * Master volume, 0.0 – 1.0.
 */
masterVolume: number, settings: Settings, };
