// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMix } from "./AudioMix";
import type { EventInfo } from "./EventInfo";
import type { Monitor } from "./Monitor";
import type { Overlay } from "./Overlay";
import type { PerScreen } from "./PerScreen";
import type { Preset } from "./Preset";
import type { Qna } from "./Qna";
import type { RunOfShow } from "./RunOfShow";
import type { RunningSteps } from "./RunningSteps";
import type { ScreenState } from "./ScreenState";
import type { Settings } from "./Settings";
import type { Source } from "./Source";
import type { Transition } from "./Transition";
import type { Trigger } from "./Trigger";
import type { Visuals } from "./Visuals";

/**
 * The whole show. This is the single source of truth.
 */
export type Show = { version: number, 
/**
 * Sources in the order they appear on screen.
 */
sources: Array<Source>, screens: PerScreen<ScreenState>, 
/**
 * The transition TAKE uses.
 */
transition: Transition, panic: boolean, panicChangedAt: number, 
/**
 * Master volume, 0.0 – 1.0.
 */
masterVolume: number, 
/**
 * When on, the Back Screen shows whatever is on the Live Screen,
 * including its transitions. Taking something on the Back Screen
 * directly turns this off.
 */
backFollowsLive: boolean, 
/**
 * The event: name, logo and emergency plan.
 */
event: EventInfo, 
/**
 * The event's segments, in running order.
 */
presets: Array<Preset>, 
/**
 * The preset picked now.
 */
activePreset: string | null, 
/**
 * Preset-button steps still running (waiting to resume). Not saved.
 */
running: Array<RunningSteps>, 
/**
 * The Stream / Hall / Recording mixes and the headphone solo.
 */
audio: AudioMix, 
/**
 * What the stage monitor shows.
 */
monitor: Monitor, 
/**
 * The run of show: cues and where it is.
 */
run: RunOfShow, 
/**
 * Overlay channels 1 – 4 (always four).
 */
overlays: Array<Overlay>, 
/**
 * The stage visuals: tempo, scene and effects, drawn by every
 * Stage visuals input.
 */
visuals: Visuals, 
/**
 * "When this happens, do that."
 */
triggers: Array<Trigger>, 
/**
 * Audience questions.
 */
qna: Qna, settings: Settings, };
