// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";

/**
 * One slide.
 */
export type Slide = { "type": "image", path: string, 
/**
 * Speaker notes (shown only on the speaker's remote).
 */
notes?: string | null, } | { "type": "input", sourceId: SourceId, 
/**
 * Speaker notes (shown only on the speaker's remote).
 */
notes?: string | null, };
