// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fit } from "./Fit";
import type { Frame } from "./Frame";
import type { Slide } from "./Slide";
import type { SourceId } from "./SourceId";

/**
 * A slideshow input.
 */
export type Slideshow = { slides: Array<Slide>, 
/**
 * The slide showing (0-based).
 */
current: number, 
/**
 * When the slide last changed (for the fade and auto-advance).
 */
changedAt: number, 
/**
 * Next slide by itself every this many ms while on air (None: by hand).
 */
autoMs: number | null, 
/**
 * After the last slide, go back to the first (with auto-advance).
 */
looping: boolean, 
/**
 * Where the slides sit, in % of the frame (the whole screen by default).
 */
area: Frame, fit: Fit, background: string, 
/**
 * An input shown behind (around) the slides — usually a camera.
 */
behind: SourceId | null, 
/**
 * Fade between slides.
 */
fade: boolean, 
/**
 * Blacked out: the slides' area shows black (what is behind stays).
 * Going to a slide brings the slides back.
 */
black: boolean, };
