// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fit } from "./Fit";

/**
 * Changes to an existing source. Fields left out stay as they are.
 */
export type SourcePatch = { name?: string, volume?: number, muted?: boolean, looping?: boolean, fit?: Fit, 
/**
 * Only for colour sources.
 */
color?: string, };
