// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adjust } from "./Adjust";
import type { ChromaKey } from "./ChromaKey";
import type { Fit } from "./Fit";
import type { SourceAudioPatch } from "./SourceAudioPatch";

/**
 * Changes to an existing source. Fields left out stay as they are.
 */
export type SourcePatch = { name?: string, volume?: number, muted?: boolean, looping?: boolean, fit?: Fit, 
/**
 * Only for colour sources.
 */
color?: string, audio?: SourceAudioPatch, 
/**
 * Green screen settings (cameras, videos and pictures).
 */
key?: ChromaKey, 
/**
 * Light, colour, crop and effects (cameras, videos and pictures).
 */
adjust?: Adjust, 
/**
 * Only for countdown inputs: the event logo picture ("" removes it).
 */
logo?: string, };
