// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFilters } from "./AudioFilters";

/**
 * Changes to a source's sound. Fields left out stay as they are.
 */
export type SourceAudioPatch = { follow?: boolean, toMaster?: boolean, toA?: boolean, toB?: boolean, delayMs?: number, filters?: AudioFilters, };
