// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auction } from './Auction';
import type { BrowserInput } from './BrowserInput';
import type { CommentCard } from './CommentCard';
import type { Countdown } from './Countdown';
import type { Credits } from './Credits';
import type { Fundraiser } from './Fundraiser';
import type { Graphic } from './Graphic';
import type { Guest } from './Guest';
import type { Logo3d } from './Logo3d';
import type { Lyrics } from './Lyrics';
import type { Pesukim } from './Pesukim';
import type { Playback } from './Playback';
import type { Poll } from './Poll';
import type { Raffle } from './Raffle';
import type { Scoreboard } from './Scoreboard';
import type { ScreenCapture } from './ScreenCapture';
import type { Scripture } from './Scripture';
import type { Seating } from './Seating';
import type { Slideshow } from './Slideshow';
import type { Split } from './Split';
import type { StreamInput } from './StreamInput';
import type { TextInput } from './TextInput';
import type { Trivia } from './Trivia';
import type { Wall } from './Wall';
import type { ZmanimCard } from './ZmanimCard';

/**
 * What a source is, with the data that kind needs.
 */
export type SourceKind =
  | { type: 'camera'; deviceId: string; label: string }
  | { type: 'video'; path: string; durationS: number; playback: Playback }
  | { type: 'image'; path: string }
  | { type: 'color'; color: string }
  | { type: 'pattern' }
  | {
      type: 'countdown';
      background: string;
      /**
       * Picture shown when the countdown finishes (the event logo).
       */
      logo?: string;
      /**
       * This input's own timer: each countdown input counts on its own,
       * so the next one can be prepared while another is on air.
       */
      timer: Countdown;
    }
  | ({ type: 'pesukim' } & Pesukim)
  | ({ type: 'text' } & TextInput)
  | ({ type: 'credits' } & Credits)
  | ({ type: 'split' } & Split)
  | ({ type: 'slideshow' } & Slideshow)
  | { type: 'visuals' }
  | ({ type: 'logo3d' } & Logo3d)
  | ({ type: 'browser' } & BrowserInput)
  | ({ type: 'stream' } & StreamInput)
  | ({ type: 'raffle' } & Raffle)
  | ({ type: 'fundraiser' } & Fundraiser)
  | ({ type: 'wall' } & Wall)
  | ({ type: 'auction' } & Auction)
  | ({ type: 'zmanim' } & ZmanimCard)
  | ({ type: 'scripture' } & Scripture)
  | ({ type: 'trivia' } & Trivia)
  | ({ type: 'seating' } & Seating)
  | ({ type: 'graphic' } & Graphic)
  | ({ type: 'guest' } & Guest)
  | ({ type: 'comment' } & CommentCard)
  | ({ type: 'poll' } & Poll)
  | ({ type: 'lyrics' } & Lyrics)
  | ({ type: 'screen' } & ScreenCapture)
  | ({ type: 'scoreboard' } & Scoreboard)
  | { type: 'microphone'; deviceId: string; label: string };
