// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adjust } from "./Adjust";
import type { CameraControls } from "./CameraControls";
import type { ChromaKey } from "./ChromaKey";
import type { Fit } from "./Fit";
import type { Playlist } from "./Playlist";
import type { Ptz } from "./Ptz";
import type { SourceAudio } from "./SourceAudio";
import type { SourceId } from "./SourceId";
import type { SourceKind } from "./SourceKind";

/**
 * One input: a camera, a video, a picture, a color…
 */
export type Source = { id: SourceId, name: string, kind: SourceKind, 
/**
 * 0.0 – 1.0
 */
volume: number, muted: boolean, looping: boolean, fit: Fit, 
/**
 * How it is heard: audio follows video, which mixes, delay.
 */
audio: SourceAudio, 
/**
 * Green / blue screen: the key color taken out (cameras, videos, pictures).
 */
key: ChromaKey, 
/**
 * Light, color, crop and effects (cameras, videos, pictures).
 */
adjust: Adjust, 
/**
 * Playback speed of a video (None: normal). 0.25 – 2.
 */
speed?: number | null, 
/**
 * A camera that can be moved over the network (PTZ).
 */
ptz?: Ptz | null, 
/**
 * A video input playing a list of videos.
 */
playlist?: Playlist | null, 
/**
 * A camera's picture held back this long, ms (to line up with sound that arrives late).
 */
videoDelayMs?: number | null, 
/**
 * A camera's own settings (zoom, focus, exposure…) and saved shots.
 */
camera?: CameraControls | null, };
