// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fit } from "./Fit";
import type { SourceId } from "./SourceId";
import type { SourceKind } from "./SourceKind";

/**
 * One input: a camera, a video, a picture, a colour…
 */
export type Source = { id: SourceId, name: string, kind: SourceKind, 
/**
 * 0.0 – 1.0
 */
volume: number, muted: boolean, looping: boolean, fit: Fit, };
