// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Countdown } from "./Countdown";
import type { Credits } from "./Credits";
import type { Pesukim } from "./Pesukim";
import type { Playback } from "./Playback";
import type { TextInput } from "./TextInput";

/**
 * What a source is, with the data that kind needs.
 */
export type SourceKind = { "type": "camera", deviceId: string, label: string, } | { "type": "video", path: string, durationS: number, playback: Playback, } | { "type": "image", path: string, } | { "type": "color", color: string, } | { "type": "pattern" } | { "type": "countdown", background: string, 
/**
 * Picture shown when the countdown finishes (the event logo).
 */
logo?: string, 
/**
 * This input's own timer: each countdown input counts on its own,
 * so the next one can be prepared while another is on air.
 */
timer: Countdown, } | { "type": "pesukim" } & Pesukim | { "type": "text" } & TextInput | { "type": "credits" } & Credits | { "type": "microphone", deviceId: string, label: string, };
