// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one source is heard.
 */
export type SourceAudio = { 
/**
 * Audio follows video: heard only while on air on the Live Screen,
 * fading with the transition. Off for microphones and music beds.
 */
follow: boolean, 
/**
 * Sent to the Stream mix (master).
 */
toMaster: boolean, 
/**
 * Sent to mix A (the hall speakers).
 */
toA: boolean, 
/**
 * Sent to mix B (the recording).
 */
toB: boolean, 
/**
 * Sound delay, to line up with the picture.
 */
delayMs: number, };
