// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adjust } from "./Adjust";
import type { ChromaKey } from "./ChromaKey";
import type { Fit } from "./Fit";
import type { Playlist } from "./Playlist";
import type { SourceAudio } from "./SourceAudio";
import type { SourceId } from "./SourceId";
import type { SourceKind } from "./SourceKind";

/**
 * One input: a camera, a video, a picture, a colour…
 */
export type Source = { id: SourceId, name: string, kind: SourceKind, 
/**
 * 0.0 – 1.0
 */
volume: number, muted: boolean, looping: boolean, fit: Fit, 
/**
 * How it is heard: audio follows video, which mixes, delay.
 */
audio: SourceAudio, 
/**
 * Green / blue screen: the key colour taken out (cameras, videos, pictures).
 */
key: ChromaKey, 
/**
 * Light, colour, crop and effects (cameras, videos, pictures).
 */
adjust: Adjust, 
/**
 * A video input playing a list of videos.
 */
playlist?: Playlist | null, };
