// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from './SourceId';

export type Speaker = {
  /**
   * The microphone they speak into.
   */
  mic: SourceId;
  name: string;
  /**
   * The line under the name (e.g. "Guest speaker"); may be empty.
   */
  title: string;
};
