// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from './SourceId';
import type { Speaker } from './Speaker';

export type SpeakerNames = {
  on: boolean;
  people: Array<Speaker>;
  /**
   * The overlay the name goes on (0 – 3, shown as 1 – 4).
   */
  channel: number;
  /**
   * The text input whose look is used (a lower third).
   */
  titleSource?: SourceId | null;
  /**
   * How long the name stays on, seconds.
   */
  holdS: number;
  /**
   * The same person's name comes on again only after this many minutes.
   */
  againMin: number;
};
