// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from './Frame';
import type { SourceId } from './SourceId';

/**
 * One box of a split screen.
 */
export type SplitBox = { sourceId: SourceId | null; frame: Frame };
