// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitBox } from "./SplitBox";
import type { SplitLayout } from "./SplitLayout";

/**
 * A split-screen input.
 */
export type Split = { layout: SplitLayout, 
/**
 * Up to four boxes; the first is at the back.
 */
boxes: Array<SplitBox>, 
/**
 * Space between boxes, % of the frame.
 */
gap: number, background: string, 
/**
 * A thin line around each box.
 */
border: boolean, borderColor: string, };
