// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenId } from "./ScreenId";
import type { SourceId } from "./SourceId";
import type { TransitionKind } from "./TransitionKind";

/**
 * One thing a preset button (or a cue) does.
 */
export type Step = { "type": "preview", screen: ScreenId, sourceId: SourceId | null, } | { "type": "take", screen: ScreenId, transition?: TransitionKind, } | { "type": "cutTo", screen: ScreenId, sourceId: SourceId, } | { "type": "blank", screens: Array<ScreenId>, value: boolean, } | { "type": "monitorMessage", text: string, } | { "type": "clearMonitorMessage" } | { "type": "startCountdown", sourceId?: SourceId, } | { "type": "pauseCountdown", sourceId?: SourceId, } | { "type": "resetCountdown", sourceId?: SourceId, } | { "type": "setCountdownLength", sourceId?: SourceId, lengthMs: number, } | { "type": "play", sourceId: SourceId, } | { "type": "pause", sourceId: SourceId, } | { "type": "backFollowsLive", value: boolean, } | { "type": "preset", presetId: string, } | { "type": "overlay", channel: number, value: boolean, } | { "type": "wait", ms: number, };
