// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stream input.
 */
export type StreamInput = { url: string, 
/**
 * Extra waiting (ms) to ride out a shaky connection (0 – 10 000).
 */
bufferMs: number, };
