// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line drawn in one movement.
 */
export type Stroke = {
  /**
   * `#rrggbb`.
   */
  color: string;
  /**
   * Thickness, as a fraction of the frame's height.
   */
  width: number;
  /**
   * Where it goes, as fractions of the frame (x, y).
   */
  points: Array<[number, number]>;
  /**
   * An arrowhead at the end.
   */
  arrow: boolean;
};
