// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Back and forth: what happens at each end.
 */
export type SwingEnds = "ease" | "pause" | "bounce";
