// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Team = {
  name: string;
  /**
   * Short name shown on the bug (e.g. "HOM").
   */
  short: string;
  color: string;
  score: number;
};
