// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextLayout } from "./TextLayout";
import type { TextStyle } from "./TextStyle";

/**
 * A text input.
 */
export type TextInput = { layout: TextLayout, 
/**
 * The main line (e.g. a name).
 */
text: string, 
/**
 * The line under it (e.g. a title); empty for none.
 */
sub: string, style: TextStyle, };
