// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlign } from "./TextAlign";
import type { TextDesign } from "./TextDesign";

/**
 * How the text looks. Sizes are in pixels of a 1920 × 1080 frame (they scale).
 */
export type TextStyle = { font: string, size: number, 
/**
 * 300 – 900.
 */
weight: number, color: string, align: TextAlign, 
/**
 * Outline width (0: none).
 */
outline: number, outlineColor: string, shadow: boolean, 
/**
 * A box behind the text.
 */
boxOn: boolean, boxColor: string, 
/**
 * 0.0 – 1.0
 */
boxOpacity: number, padding: number, radius: number, 
/**
 * Line height, × the size.
 */
lineHeight: number, 
/**
 * Letter spacing in px.
 */
letterSpacing: number, 
/**
 * Ticker speed, px per second.
 */
speed: number, design: TextDesign, 
/**
 * The accent colour (bar, line, name box).
 */
accent: string, 
/**
 * Builds on with an animation when it comes on.
 */
animate: boolean, };
