// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a title comes on (when it builds on).
 */
export type TextEntrance = "build" | "fade" | "slide" | "rise" | "pop";
