// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The design of the text's background.
 */
export type TextDesign = 'box' | 'bar' | 'split' | 'underline' | 'gradient' | 'glass';
