// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlign } from "./TextAlign";
import type { TextDesign } from "./TextDesign";
import type { TextEntrance } from "./TextEntrance";

/**
 * How the text looks. Sizes are in pixels of a 1920 × 1080 frame (they scale).
 */
export type TextStyle = { font: string, size: number, 
/**
 * 300 – 900.
 */
weight: number, color: string, align: TextAlign, 
/**
 * Outline width (0: none).
 */
outline: number, outlineColor: string, shadow: boolean, 
/**
 * A box behind the text.
 */
boxOn: boolean, boxColor: string, 
/**
 * 0.0 – 1.0
 */
boxOpacity: number, padding: number, radius: number, 
/**
 * Line height, × the size.
 */
lineHeight: number, 
/**
 * Letter spacing in px.
 */
letterSpacing: number, 
/**
 * Ticker speed, px per second.
 */
speed: number, design: TextDesign, 
/**
 * The accent colour (bar, line, name box).
 */
accent: string, 
/**
 * Builds on with an animation when it comes on.
 */
animate: boolean, 
/**
 * How it comes on (when it animates).
 */
entrance: TextEntrance, italic: boolean, 
/**
 * ALL CAPITALS.
 */
uppercase: boolean, 
/**
 * The second line's colour ("" for the same as the first).
 */
subColor: string, 
/**
 * The second line's size, in % of the first.
 */
subSize: number, 
/**
 * The second line's font ("" for the same as the first).
 */
subFont: string, 
/**
 * A line around the box, px (0: none).
 */
border: number, borderColor: string, 
/**
 * A lower third's distance from the side of the screen, % of the width.
 */
x: number, 
/**
 * A lower third's distance from the bottom of the screen, % of the height.
 */
y: number, };
