// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the countdown's time is written.
 */
export type TimerFormat = "auto" | "minSec" | "hourMinSec";
