// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One field's value: `{{key}}` in the template becomes `value`.
 */
export type TitlerValue = { key: string, value: string, };
