// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";
import type { TitlerTable } from "./TitlerTable";
import type { TitlerValue } from "./TitlerValue";

/**
 * A Titler graphic input.
 */
export type TitlerGraphic = { 
/**
 * The `.lumtitle` project, as JSON text.
 */
template: string, 
/**
 * The fields as the operator set them (fields left out show their sample).
 */
values: Array<TitlerValue>, 
/**
 * The scoreboard input whose teams, scores and clock fill score fields
 * (None: the first scoreboard of the event).
 */
scoreboard: SourceId | null, 
/**
 * The template's own data sources as last read (by the control window).
 */
data: Array<TitlerTable>, 
/**
 * The row the operator chose for them (from 0; None: each source's own row).
 */
dataRow: number | null, };
