// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionKind } from "./TransitionKind";

/**
 * A transition type together with its length.
 */
export type Transition = { kind: TransitionKind, durationMs: number, };
