// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds of transition between two sources.
 */
export type TransitionKind = "cut" | "fade" | "merge" | "dip" | "wipe" | "slide" | "wipeLeft" | "wipeDown" | "wipeUp" | "slideRight" | "slideDown" | "slideUp" | "cover" | "reveal" | "split" | "splitVertical" | "iris" | "diamond" | "zoom" | "zoomOut" | "blur" | "flash" | "stinger1" | "stinger2";
