// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds of transition between two sources.
 */
export type TransitionKind = "cut" | "fade" | "merge" | "dip" | "wipe" | "slide";
