// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from "./Step";
import type { When } from "./When";

/**
 * One trigger.
 */
export type Trigger = { id: string, name: string, enabled: boolean, when: When, steps: Array<Step>, 
/**
 * When it last went off.
 */
lastFired: number, };
