// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TriviaAnswer = {
  key: string;
  option: number;
  /**
   * Milliseconds after the question was asked.
   */
  afterMs: number;
};
