// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Words on the visuals.
 */
export type VisualsText = { on: boolean, words: string, 
/**
 * clean, bold, elegant or classic.
 */
font: string, color: string, size: number, 
/**
 * Up / down, -0.4 – 0.4.
 */
y: number, 
/**
 * Pulses with the beat.
 */
pulse: number, };
