// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneRef } from "./SceneRef";

/**
 * Effects on the picture (all saved in looks).
 */
export type VisualsFx = { zoom: number, 
/**
 * Turns with the beat.
 */
spin: number, panX: number, panY: number, 
/**
 * Zoom kick on the beat.
 */
pump: number, 
/**
 * Kaleidoscope segments (0: off).
 */
kal: number, 
/**
 * 0 off, 1 – 3 mirror modes.
 */
mirror: number, hue: number, hueCycle: number, sat: number, con: number, glow: number, trail: number, echo: number, echoRot: number, rgb: number, pix: number, post: number, scan: number, vig: number, 
/**
 * Overlay layer: a second scene on top.
 */
ov: number, ovMode: number, ovScene: SceneRef, };
