// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneRef } from './SceneRef';
import type { VisualsFx } from './VisualsFx';
import type { VisualsLogo } from './VisualsLogo';
import type { VisualsSettings } from './VisualsSettings';
import type { VisualsText } from './VisualsText';

/**
 * Change the held pads and toggles, the settings, effects or words. Only
 * what is given changes.
 */
export type VisualsPatch = {
  settings?: VisualsSettings;
  fx?: VisualsFx;
  text?: VisualsText;
  strobe?: boolean;
  blackout?: boolean;
  invert?: boolean;
  freeze?: boolean;
  favourites?: Array<SceneRef>;
  logo?: VisualsLogo;
};
