// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogoPlace } from "./LogoPlace";

/**
 * The event logo on top of the visuals.
 */
export type VisualsLogo = { on: boolean, place: LogoPlace, 
/**
 * Height as a share of the screen, 0.05 – 0.6.
 */
size: number, 
/**
 * Grows a little on the beat, 0 – 1.
 */
pulse: number, };
