// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quantize } from "./Quantize";

/**
 * How the visuals play (not part of looks).
 */
export type VisualsSettings = { 
/**
 * Flash strength on the beat, 0 – 1.
 */
flash: number, 
/**
 * Movement speed, 0.25 – 2.
 */
speed: number, bright: number, 
/**
 * "scene" (each scene's own colors) or a color set's key.
 */
palette: string, 
/**
 * Fade between scenes in beats; negative: the music type's own.
 */
fade: number, quantize: Quantize, 
/**
 * Change scene by itself every this many bars (0: off).
 */
autoBars: number, autoRandom: boolean, 
/**
 * A new music type sets its own tempo.
 */
bankTempo: boolean, 
/**
 * Flash every this many beats (0: never).
 */
flashEvery: number, 
/**
 * Strobe flashes per beat.
 */
strobeDiv: number, slowBlackout: boolean, 
/**
 * Drawing quality: 1, 0.75 or 0.5.
 */
quality: number, 
/**
 * Safe for the audience: no strobe, gentler flashes (flashing light
 * can affect people with photosensitive epilepsy).
 */
safe: boolean, };
