// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneRef } from './SceneRef';
import type { VisualsFx } from './VisualsFx';

/**
 * A saved look: a scene and every effect setting.
 */
export type VisualsLook = { scene: SceneRef; fx: VisualsFx };
