// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneRef } from './SceneRef';
import type { VisualsFx } from './VisualsFx';
import type { VisualsLogo } from './VisualsLogo';
import type { VisualsLook } from './VisualsLook';
import type { VisualsSettings } from './VisualsSettings';
import type { VisualsText } from './VisualsText';

/**
 * Everything about the stage visuals.
 */
export type Visuals = {
  bpm: number;
  /**
   * The beat is `anchor_beat` at `anchor_at` and moves on at `bpm`.
   */
  anchorAt: number;
  anchorBeat: number;
  /**
   * The scene on (or coming, at `fade_start`).
   */
  scene: SceneRef;
  /**
   * The scene fading out.
   */
  from: SceneRef | null;
  /**
   * The beat the fade starts on (can be ahead: the change waits for it).
   */
  fadeStart: number;
  /**
   * Fade length in beats (0: a cut).
   */
  fadeLen: number;
  /**
   * The beat to change scene by itself (auto-change).
   */
  nextAuto: number | null;
  settings: VisualsSettings;
  fx: VisualsFx;
  text: VisualsText;
  /**
   * Held pads and toggles.
   */
  strobe: boolean;
  blackout: boolean;
  invert: boolean;
  /**
   * Frozen on this beat.
   */
  frozen: number | null;
  /**
   * The last white flash.
   */
  flashAt: number;
  /**
   * Saved looks 1 – 8.
   */
  looks: Array<VisualsLook | null>;
  /**
   * Scenes starred to find quickly.
   */
  favourites: Array<SceneRef>;
  logo: VisualsLogo;
};
