// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WallMessage = { id: number, 
/**
 * Who sent it (may be empty).
 */
name: string, text: string, 
/**
 * A photo sent with it (a file on this computer), or empty.
 */
photo: string, at: number, 
/**
 * Let through to the screen.
 */
approved: boolean, };
