// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the wall looks on screen.
 */
export type WallStyle = "cards" | "grid" | "ticker";
