// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WallMessage } from "./WallMessage";
import type { WallStyle } from "./WallStyle";

export type Wall = { title: string, 
/**
 * What the phones are asked ("Write a blessing for the couple").
 */
prompt: string, messages: Array<WallMessage>, 
/**
 * Phones may send now.
 */
open: boolean, 
/**
 * Phones may send a photo too.
 */
photos: boolean, 
/**
 * Messages from phones show straight away (else the operator lets each through).
 */
autoApprove: boolean, style: WallStyle, 
/**
 * Seconds each message stays (one at a time).
 */
seconds: number, 
/**
 * Keep this message on screen (instead of taking turns).
 */
pinned: number | null, nextId: number, joinUrl: string, joinQr: string, showJoin: boolean, };
