// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BroadcastWhat } from './BroadcastWhat';
import type { ScreenId } from './ScreenId';
import type { SourceId } from './SourceId';

/**
 * What sets a trigger off.
 */
export type When =
  | { type: 'videoEnds'; sourceId: SourceId }
  | { type: 'onAir'; sourceId: SourceId; screen: ScreenId | null }
  | { type: 'offAir'; sourceId: SourceId; screen: ScreenId | null }
  | { type: 'countdownZero'; sourceId: SourceId }
  | { type: 'atTime'; minute: number; utcOffsetMin: number }
  | { type: 'videoTimeLeft'; sourceId: SourceId; seconds: number }
  | { type: 'inputLost'; sourceId: SourceId }
  | { type: 'inputBack'; sourceId: SourceId }
  | {
      type: 'sound';
      sourceId: SourceId;
      /**
       * Above the level (someone talks) or below it (quiet).
       */
      above: boolean;
      /**
       * The level, in dB below full scale (-60 – 0).
       */
      db: number;
      /**
       * How long it has to stay that way first.
       */
      holdMs: number;
    }
  | { type: 'broadcast'; what: BroadcastWhat; on: boolean };
