// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenId } from './ScreenId';
import type { SourceId } from './SourceId';

/**
 * What sets a trigger off.
 */
export type When =
  | { type: 'videoEnds'; sourceId: SourceId }
  | { type: 'onAir'; sourceId: SourceId; screen: ScreenId | null }
  | { type: 'offAir'; sourceId: SourceId; screen: ScreenId | null }
  | { type: 'countdownZero'; sourceId: SourceId }
  | { type: 'atTime'; minute: number; utcOffsetMin: number };
