// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the zmanim input looks.
 */
export type ZmanimStyle = 'card' | 'bar' | 'countdown';
