//! The DeckLink API's COM interfaces Lumora uses, written out by hand.
//!
//! Desktop Video (Blackmagic's free driver, installed by the user) registers
//! the API as COM classes; nothing of Blackmagic's is shipped with Lumora.
//! These definitions follow the interface files of DeckLink SDK 12.0, whose
//! license reads:
//!
//! > Copyright (c) 2021 Blackmagic Design
//! >
//! > Permission is hereby granted, free of charge, to any person or
//! > organization obtaining a copy of the software and accompanying
//! > documentation covered by this license (the "Software") to use,
//! > reproduce, display, distribute, execute, and transmit the Software, and
//! > to prepare derivative works of the Software, and to permit third-parties
//! > to whom the Software is furnished to do so, all subject to the
//! > following:
//! >
//! > The copyright notices in the Software and this entire statement,
//! > including the above license grant, this restriction and the following
//! > disclaimer, must be included in all copies of the Software, in whole or
//! > in part, and all derivative works of the Software, unless such copies
//! > or derivative works are solely in the form of machine-executable object
//! > code generated by a source language processor.
//! >
//! > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//! > OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//! > MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
//! > NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
//! > DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
//! > WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//! > CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//! > SOFTWARE.
//!
//! Only the interfaces and methods Lumora calls are here. A COM vtable is
//! read in order, so every method up to the last one used is listed, in the
//! SDK's order, even when Lumora never calls it. Interface pointers are
//! passed as raw pointers and wrapped with `from_raw` / `from_raw_borrowed`.
#![allow(
    non_snake_case,
    clippy::upper_case_acronyms,
    clippy::too_many_arguments
)]

use std::ffi::c_void;

use windows_core::{interface, IUnknown, IUnknown_Vtbl, BSTR, GUID, HRESULT};

/// `CDeckLinkIterator`: lists the cards.
pub const CLSID_DECKLINK_ITERATOR: GUID = GUID::from_u128(0xBA6C6F44_6DA5_4DCE_94AA_EE2D1372A676);

/// Windows' `BOOL`.
pub type Bool = i32;

#[interface("50FB36CD-3063-4B73-BDBB-958087F2D8BA")]
pub unsafe trait IDeckLinkIterator: IUnknown {
    pub fn Next(&self, deckLink: *mut *mut c_void) -> HRESULT;
}

#[interface("C418FBDD-0587-48ED-8FE5-640F0A14AF91")]
pub unsafe trait IDeckLink: IUnknown {
    pub fn GetModelName(&self, name: *mut BSTR) -> HRESULT;
    pub fn GetDisplayName(&self, name: *mut BSTR) -> HRESULT;
}

#[interface("17D4BF8E-4911-473A-80A0-731CF6FF345B")]
pub unsafe trait IDeckLinkProfileAttributes: IUnknown {
    pub fn GetFlag(&self, id: u32, value: *mut Bool) -> HRESULT;
    pub fn GetInt(&self, id: u32, value: *mut i64) -> HRESULT;
    pub fn GetFloat(&self, id: u32, value: *mut f64) -> HRESULT;
    pub fn GetString(&self, id: u32, value: *mut BSTR) -> HRESULT;
}

#[interface("912F634B-2D4E-40A4-8AAB-8D80B73F1289")]
pub unsafe trait IDeckLinkConfiguration: IUnknown {
    pub fn SetFlag(&self, id: u32, value: Bool) -> HRESULT;
    pub fn GetFlag(&self, id: u32, value: *mut Bool) -> HRESULT;
    pub fn SetInt(&self, id: u32, value: i64) -> HRESULT;
    pub fn GetInt(&self, id: u32, value: *mut i64) -> HRESULT;
}

#[interface("9C88499F-F601-4021-B80B-032E4EB41C35")]
pub unsafe trait IDeckLinkDisplayModeIterator: IUnknown {
    pub fn Next(&self, mode: *mut *mut c_void) -> HRESULT;
}

#[interface("3EB2C1AB-0A3D-4523-A3AD-F40D7FB14E78")]
pub unsafe trait IDeckLinkDisplayMode: IUnknown {
    pub fn GetName(&self, name: *mut BSTR) -> HRESULT;
    pub fn GetDisplayMode(&self) -> u32;
    pub fn GetWidth(&self) -> i32;
    pub fn GetHeight(&self) -> i32;
    pub fn GetFrameRate(&self, duration: *mut i64, scale: *mut i64) -> HRESULT;
    pub fn GetFieldDominance(&self) -> u32;
    pub fn GetFlags(&self) -> u32;
}

#[interface("BC6CFBD3-8317-4325-AC1C-1216391E9340")]
pub unsafe trait IDeckLinkTimecode: IUnknown {
    pub fn GetBCD(&self) -> u32;
    pub fn GetComponents(
        &self,
        hours: *mut u8,
        minutes: *mut u8,
        seconds: *mut u8,
        frames: *mut u8,
    ) -> HRESULT;
}

#[interface("3F716FE0-F023-4111-BE5D-EF4414C05B17")]
pub unsafe trait IDeckLinkVideoFrame: IUnknown {
    pub fn GetWidth(&self) -> i32;
    pub fn GetHeight(&self) -> i32;
    pub fn GetRowBytes(&self) -> i32;
    pub fn GetPixelFormat(&self) -> u32;
    pub fn GetFlags(&self) -> u32;
    pub fn GetBytes(&self, buffer: *mut *mut c_void) -> HRESULT;
    pub fn GetTimecode(&self, format: u32, timecode: *mut *mut c_void) -> HRESULT;
    pub fn GetAncillaryData(&self, ancillary: *mut *mut c_void) -> HRESULT;
}

#[interface("69E2639F-40DA-4E19-B6F2-20ACE815C390")]
pub unsafe trait IDeckLinkMutableVideoFrame: IDeckLinkVideoFrame {
    pub fn SetFlags(&self, flags: u32) -> HRESULT;
}

#[interface("05CFE374-537C-4094-9A57-680525118F44")]
pub unsafe trait IDeckLinkVideoInputFrame: IDeckLinkVideoFrame {
    pub fn GetStreamTime(&self, time: *mut i64, duration: *mut i64, scale: i64) -> HRESULT;
}

#[interface("E43D5870-2894-11DE-8C30-0800200C9A66")]
pub unsafe trait IDeckLinkAudioInputPacket: IUnknown {
    pub fn GetSampleFrameCount(&self) -> i32;
    pub fn GetBytes(&self, buffer: *mut *mut c_void) -> HRESULT;
    pub fn GetPacketTime(&self, time: *mut i64, scale: i64) -> HRESULT;
}

#[interface("C6FCE4C9-C4E4-4047-82FB-5D238232A902")]
pub unsafe trait IDeckLinkInputCallback: IUnknown {
    pub fn VideoInputFormatChanged(&self, events: u32, mode: *mut c_void, detected: u32)
        -> HRESULT;
    pub fn VideoInputFrameArrived(&self, video: *mut c_void, audio: *mut c_void) -> HRESULT;
}

#[interface("C21CDB6E-F414-46E4-A636-80A566E0ED37")]
pub unsafe trait IDeckLinkInput: IUnknown {
    pub fn DoesSupportVideoMode(
        &self,
        connection: u32,
        mode: u32,
        pixel_format: u32,
        conversion: u32,
        flags: u32,
        actual: *mut u32,
        supported: *mut Bool,
    ) -> HRESULT;
    pub fn GetDisplayMode(&self, mode: u32, result: *mut *mut c_void) -> HRESULT;
    pub fn GetDisplayModeIterator(&self, iterator: *mut *mut c_void) -> HRESULT;
    pub fn SetScreenPreviewCallback(&self, callback: *mut c_void) -> HRESULT;
    pub fn EnableVideoInput(&self, mode: u32, pixel_format: u32, flags: u32) -> HRESULT;
    pub fn DisableVideoInput(&self) -> HRESULT;
    pub fn GetAvailableVideoFrameCount(&self, count: *mut u32) -> HRESULT;
    pub fn SetVideoInputFrameMemoryAllocator(&self, allocator: *mut c_void) -> HRESULT;
    pub fn EnableAudioInput(&self, rate: u32, sample_type: u32, channels: u32) -> HRESULT;
    pub fn DisableAudioInput(&self) -> HRESULT;
    pub fn GetAvailableAudioSampleFrameCount(&self, count: *mut u32) -> HRESULT;
    pub fn StartStreams(&self) -> HRESULT;
    pub fn StopStreams(&self) -> HRESULT;
    pub fn PauseStreams(&self) -> HRESULT;
    pub fn FlushStreams(&self) -> HRESULT;
    pub fn SetCallback(&self, callback: *mut c_void) -> HRESULT;
}

#[interface("BE2D9020-461E-442F-84B7-E949CB953B9D")]
pub unsafe trait IDeckLinkOutput: IUnknown {
    pub fn DoesSupportVideoMode(
        &self,
        connection: u32,
        mode: u32,
        pixel_format: u32,
        conversion: u32,
        flags: u32,
        actual: *mut u32,
        supported: *mut Bool,
    ) -> HRESULT;
    pub fn GetDisplayMode(&self, mode: u32, result: *mut *mut c_void) -> HRESULT;
    pub fn GetDisplayModeIterator(&self, iterator: *mut *mut c_void) -> HRESULT;
    pub fn SetScreenPreviewCallback(&self, callback: *mut c_void) -> HRESULT;
    pub fn EnableVideoOutput(&self, mode: u32, flags: u32) -> HRESULT;
    pub fn DisableVideoOutput(&self) -> HRESULT;
    pub fn SetVideoOutputFrameMemoryAllocator(&self, allocator: *mut c_void) -> HRESULT;
    pub fn CreateVideoFrame(
        &self,
        width: i32,
        height: i32,
        row_bytes: i32,
        pixel_format: u32,
        flags: u32,
        frame: *mut *mut c_void,
    ) -> HRESULT;
    pub fn CreateAncillaryData(&self, pixel_format: u32, out: *mut *mut c_void) -> HRESULT;
    pub fn DisplayVideoFrameSync(&self, frame: *mut c_void) -> HRESULT;
}

// Attribute, configuration and flag numbers (four-letter codes).
use crate::modes::fourcc;

pub const ATTR_SUPPORTS_INPUT_FORMAT_DETECTION: u32 = fourcc(b"infd");
pub const ATTR_MAXIMUM_AUDIO_CHANNELS: u32 = fourcc(b"mach");
pub const ATTR_PERSISTENT_ID: u32 = fourcc(b"peid");
pub const ATTR_VIDEO_INPUT_CONNECTIONS: u32 = fourcc(b"vicn");
pub const ATTR_VIDEO_OUTPUT_CONNECTIONS: u32 = fourcc(b"vocn");
pub const ATTR_VIDEO_IO_SUPPORT: u32 = fourcc(b"vios");
pub const CONFIG_VIDEO_INPUT_CONNECTION: u32 = fourcc(b"vicn");
/// `bmdDeviceSupportsCapture`, `bmdDeviceSupportsPlayback`.
pub const IO_CAPTURE: i64 = 1;
pub const IO_PLAYBACK: i64 = 2;
/// `bmdVideoInputEnableFormatDetection`.
pub const INPUT_ENABLE_FORMAT_DETECTION: u32 = 1;
/// `bmdFrameHasNoInputSource`.
pub const FRAME_HAS_NO_INPUT_SOURCE: u32 = 1 << 31;
/// `bmdVideoInputDisplayModeChanged`.
pub const FORMAT_CHANGED_DISPLAY_MODE: u32 = 1;
/// `bmdTimecodeRP188Any`, `bmdTimecodeVITC`.
pub const TIMECODE_RP188_ANY: u32 = fourcc(b"rp18");
pub const TIMECODE_VITC: u32 = fourcc(b"vitc");
/// `bmdAudioSampleRate48kHz`, `bmdAudioSampleType32bitInteger`.
pub const AUDIO_48K: u32 = 48_000;
pub const AUDIO_32BIT: u32 = 32;
/// `bmdVideoOutputFlagDefault`, `bmdFrameFlagDefault`, `bmdNoVideoOutputConversion`, `bmdSupportedVideoModeDefault`.
pub const OUTPUT_DEFAULT: u32 = 0;
pub const NO_CONVERSION: u32 = fourcc(b"none");
